version: '2'
services:
  jenkins-dind:
    image: linwenjun/jenkins-dind:1.0.0
    ports:
      - "8088:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker